=== MontiSecArc/msa_policies/Policies/resources/de/montisecarc/policies/PolicyConfiguration.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="http://www.tbuning.de"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Policies" type="tbun:PoliciesType" xmlns:tbun="http://www.tbuning.de"/>
    <xs:complexType name="PoliciesType">
        <xs:sequence>
            <xs:element type="tbun:PolicyType" name="Policy" xmlns:tbun="http://www.tbuning.de"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="PolicyType">
        <xs:sequence>
            <xs:element type="tbun:GraphQueryInspectionType" name="GraphQueryInspection"
                        xmlns:tbun="http://www.tbuning.de"/>
            <xs:element type="tbun:GraphQueryFixType" name="GraphQueryFix" xmlns:tbun="http://www.tbuning.de"/>
        </xs:sequence>
        <xs:attribute type="xs:string" name="id"/>
        <xs:attribute type="xs:string" name="name"/>
        <xs:attribute type="xs:string" name="severity"/>
    </xs:complexType>
    <xs:complexType name="GraphQueryFixType">
        <xs:sequence>
            <xs:element type="xs:string" name="Path"/>
            <xs:element type="xs:string" name="FixDescription"/>
        </xs:sequence>
    </xs:complexType>
    <xs:complexType name="GraphQueryInspectionType">
        <xs:sequence>
            <xs:element type="xs:string" name="Path"/>
            <xs:element type="xs:string" name="ProblemDescription"/>
        </xs:sequence>
    </xs:complexType>
</xs:schema>

=== MontiSecArc/msa_policies/build/libs/MSA_Policies-0.7.8/PolicyConfiguration.xml
<?xml version="1.0" encoding="UTF-8" ?>
<Policies xmlns="http://www.tbuning.de"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://www.tbuning.de PolicyConfiguration.xsd">
    <Policy name="Unused Port" severity="LIKE_UNUSED_SYMBOL">
        <GraphQueryInspection>
            <Path>inspections/UnusedPortInspection.cyp</Path>
            <ProblemDescription>Error!!</ProblemDescription>
        </GraphQueryInspection>
        <GraphQueryFix>
            <Path>inspections/UnusedPortInspection.cyp</Path>
            <FixDescription>Error!!</FixDescription>
        </GraphQueryFix>
    </Policy>
</Policies>
